### ISSUE TITLE
Asciidoctor 2.0.0.rc1 does not function with the extension

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#170]
On VS Code 1.32  I receive the following error using the pre-release Asciidoctor 2.0.0.rc.1

```
undefined method `<=' for nil:NilClass undefined method `<=' for nil:NilClass

command: asciidoctor -q -o- - -B "/media/mulhollandd/KINGSTON/standard-designs/transformer-protection/SEL487E-3_Transformer_Protection_Settings/setting_guide""

If the asciidoctor binary is not in your PATH, you can set the full path.
Go to `File -> Preferences -> User settings` and adjust the asciidoc.asciidoctor_command
```

However from a terminal window:

```
$ asciidoctor -V
Asciidoctor 2.0.0.rc.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

It renders correctly when using asciidoctor.js and also using Asciidoctor 1.5.8.

The problem, presumably is https://github.com/asciidoctor/asciidoctor-vscode/blob/3a405f72f0e29bcf98cdc7dfc4413c203764c03e/src/text-parser.ts#L108 or upstream with Asciidoctor 2.0.0.

But the command above looks strange to me because it doesn't show the file name I am trying to convert -- ah -- I see it's writing to stdin.

The full command equivalent from the command line would be:

`asciidoctor -q -o- - -B "/media/mulhollandd/KINGSTON/standard-designs/transformer-protection/SEL487E-3_Transformer_Protection_Settings/setting_guide" Setting_Guide.adoc `

But with `-q` it doesn't make sense because stdin would normally be passed. If `-q` is removed it produces output but the warning, `asciidoctor: WARNING: extra arguments detected (unparsed arguments: '-', 'Setting_Guide.adoc') or incorrect usage of stdin`

I try to get a stacktrace by running:

```
21:10 $ asciidoctor -q -o- - -B "/media/mulhollandd/KINGSTON/standard-designs/transformer-protection/SEL487E-3_Transformer_Protection_Settings/setting_guide" Setting_Guide.adoc --trace
asciidoctor: WARNING: extra arguments detected (unparsed arguments: '-', 'Setting_Guide.adoc') or incorrect usage of stdin
Traceback (most recent call last):
        71: from /usr/local/bin/asciidoctor:23:in `<main>'
        70: from /usr/local/bin/asciidoctor:23:in `load'
        69: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/bin/asciidoctor:15:in `<top (required)>'
        68: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/cli/invoker.rb:109:in `invoke!'
        67: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/cli/invoker.rb:109:in `each'
        66: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/cli/invoker.rb:126:in `block in invoke!'
        65: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor.rb:1530:in `convert_file'
        64: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor.rb:1530:in `open'
        63: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor.rb:1530:in `block in convert_file'
        62: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor.rb:1465:in `convert'
        61: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/document.rb:925:in `convert'
        60: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter.rb:380:in `convert'
        59: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:176:in `document'
        58: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/document.rb:994:in `content'
        57: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `content'
        56: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `map'
        55: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `block in content'
        54: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:81:in `convert'
        53: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter.rb:380:in `convert'
        52: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:357:in `section'
        51: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `content'
        50: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `map'
        49: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `block in content'
        48: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:81:in `convert'
        47: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter.rb:380:in `convert'
        46: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:358:in `section'
        45: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `content'
        44: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `map'
        43: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `block in content'
        42: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:81:in `convert'
        41: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter.rb:380:in `convert'
        40: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:358:in `section'
        39: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `content'
        38: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `map'
        37: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `block in content'
        36: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:81:in `convert'
        35: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter.rb:380:in `convert'
        34: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:358:in `section'
        33: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `content'
        32: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `map'
        31: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `block in content'
        30: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:81:in `convert'
        29: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter.rb:380:in `convert'
        28: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:695:in `open'
        27: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/block.rb:111:in `content'
        26: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `content'
        25: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `map'
        24: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `block in content'
        23: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/list.rb:30:in `convert'
        22: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:81:in `convert'
        21: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter.rb:380:in `convert'
        20: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:655:in `olist'
        19: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:655:in `each'
        18: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:664:in `block in olist'
        17: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `content'
        16: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `map'
        15: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:90:in `block in content'
        14: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/list.rb:30:in `convert'
        13: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/abstract_block.rb:81:in `convert'
        12: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter.rb:380:in `convert'
        11: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:902:in `ulist'
        10: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:902:in `each'
         9: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/converter/html5.rb:913:in `block in ulist'
         8: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/list.rb:80:in `text'
         7: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/substitutors.rb:92:in `apply_subs'
         6: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/substitutors.rb:92:in `each'
         5: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/substitutors.rb:103:in `block in apply_subs'
         4: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/substitutors.rb:905:in `sub_macros'
         3: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/substitutors.rb:939:in `sub_inline_xrefs'
         2: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/substitutors.rb:939:in `gsub'
         1: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/substitutors.rb:1021:in `block in sub_inline_xrefs'
/usr/lib/ruby/2.5.0/logger.rb:323:in `debug?': undefined method `<=' for nil:NilClass (NoMethodError)
```

**Comment by danyill** [comment]
I don't think this is an issue with the extension, I think it is an issue with Asciidoctor as I can reproduce a simple test case without this extension at all.

e.g. https://gist.github.com/danyill/55ab9b7304eb27f013dbbac549f9e9ef

I'll take this up in the core. Sorry for the churn.
