### ISSUE TITLE
ERR tokens.filter is not a function: TypeError: tokens.filter is not a function

### ISSUE THREAD

**Issue by mimijava** [asciidoctor/asciidoctor-vscode#190]
Version v2.5.2

 ERR tokens.filter is not a function: TypeError: tokens.filter is not a function
	at AsciidocFoldingProvider.<anonymous> (C:\Users\h00325234\.vscode\extensions\joaompinto.asciidoctor-vscode-2.5.2\out\src\features\foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\h00325234\.vscode\extensions\joaompinto.asciidoctor-vscode-2.5.2\out\src\features\foldingProvider.js:8:58)

**Comment by MatteoCampinoti94** [comment]
We are aware of the problem, folding and symbols have been broken since VSCode 1.28. We'll be fixing them in the future, but we need to overhaul them and we aren't 100% of what exactly is the problem (tokens.filter does not throw an error with the linter or during compilation).

At the moment the only problem it's causing is showing that error message, nothing else.
