### ISSUE TITLE
Error converting to PDF, TypeError: Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by Phillipus** [asciidoctor/asciidoctor-vscode#214]
## Description

"Export Document as PDF" not working on Mac.

Error reported:

> Error converting to PDF, TypeError: Cannot read property 'write' of undefined

## System Information

Mac, OS X 10.12.6.
VSCode 1.36.1
Asciidoctor extension 2.7.6
All Asciidoctor settings are default.

## To Reproduce

Steps to reproduce the issue:

1. Create an .adoc file
2. Choose command "Export Document as PDF".

## Screenshots & Files

(none)

## Additional Context

This works OK on Windows, just not Mac.

**Comment by Phillipus** [comment]
I have a fix for this problem...

Here's the interesting part of the console log:

```
notificationsAlerts.ts:40 Error converting to PDF, TypeError: Cannot read property 'write' of undefined
onDidNotificationChange @ notificationsAlerts.ts:40
log.ts:173   ERR spawn /Users/phillipus/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.6/out/src/commands/wkhtmltopdf-darwin-x64 EACCES: Error: spawn /Users/phillipus/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.6/out/src/commands/wkhtmltopdf-darwin-x64 EACCES
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)

```

So I guessed that file `wkhtmltopdf-darwin-x64` was not executing and sure enough the file did not have the executable bit set. So I set the file to be be executable and the PDF converter now works.

BTW - there was an error when the installation of `wkhtmltopdf` first ran.

**Comment by Phillipus** [comment]
When I uninstalled and re-installed Asciidoctor extension this problem did not occur. So I'll close this issue.
