### ISSUE TITLE
Errors in Log (Extension Host)

### ISSUE THREAD

**Issue by serialprimate** [asciidoctor/asciidoctor-vscode#243]
Hi there,

I'm getting the following error with this extension V2.7.7 with VSCode 1.41.1. I am new to asciidoc and just made a hello world document.

```
[2020-01-11 13:31:54.367] [exthost] [error] TypeError: Cannot read property 'filter' of null
	at AsciidocFoldingProvider.<anonymous> (/home/matt/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.7/out/src/features/foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (/home/matt/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.7/out/src/features/foldingProvider.js:8:58)
```
and

```
[2020-01-11 13:45:06.826] [exthost] [error] [joaompinto.asciidoctor-vscode] provider FAILED
[2020-01-11 13:45:06.826] [exthost] [error] TypeError: tokens.filter is not a function
	at AsciidocFoldingProvider.<anonymous> (/home/matt/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.7/out/src/features/foldingProvider.js:29:42)
	at Generator.next (<anonymous>)
	at fulfilled (/home/matt/.vscode/extensions/joaompinto.asciidoctor-vscode-2.7.7/out/src/features/foldingProvider.js:8:58)
```
My Asciidoc file is
```
= Hi

Hello.
```

As a completely separate note, I have also noticed that Asciidoctor errors are not reported to the terminal or the problems view.

Matt

**Comment by danyill** [comment]
The `foldingProvider` is now disabled so I think these errors should no longer be present.

**Comment by Mogztter** [comment]
@serialprimate Closing, please reopen if you still see these errors on the latest version (2.8.9)
