### ISSUE TITLE
Blank live preview

### ISSUE THREAD

**Issue by shpaggin** [asciidoctor/asciidoctor-vscode#261]
Live preview no longer works for me - nothing get displayed at all. I think this happened after the extension updated to 2.7.9, since before I had no issues. I noticed this popped up before: https://github.com/asciidoctor/asciidoctor-vscode/issues/191

OS: MacOS Mojave 10.14.6 
VSCode version: 1.41.1
Asciidoc extension: 2.7.9
Asciidoctor: 2.0.10
Ruby: 2.3.7p456

Visual Studio Code Version
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by joaompinto** [comment]
Can you please share a sample AsciiDoc content that causes the issue for you ?

Thanks

**Comment by shpaggin** [comment]
Hmm I thought it wasn't working at all, but after some testing, I found that the content that breaks the preview is having:

[id="sample-id_{context}"]

At the beginning of the file. When I remove that, or write a new file without an ID, the preview works completely fine. However, the ID didn't seem to be an issue in 2.7.8

**Comment by danyill** [comment]
@shpaggin I tried an example like that in 2.7.9 and it seemed to work OK:

![image](https://user-images.githubusercontent.com/674783/73882498-0eaafc80-48c7-11ea-858e-4ce19b36bcc9.png)

![image](https://user-images.githubusercontent.com/674783/73882641-4dd94d80-48c7-11ea-9bfe-66b94d9744a4.png)

Could it be anything else? Is `context` set or holding a value?

**Comment by KLynn2019** [comment]
We're seeing this issue as well. The preview is displaying for some files but not for others. It's not clear where the difference is...but we had no problem with 2.7.8.

![image](https://user-images.githubusercontent.com/51419423/73887576-d5787b00-4839-11ea-9619-ee395208017f.png)

![image](https://user-images.githubusercontent.com/51419423/73887592-dad5c580-4839-11ea-9235-0d150a482628.png)

**Comment by joaompinto** [comment]
It really would be great if someone could provide a minimal sample that breaks rendering (in text format) that we could copy/paste :)

**Comment by KLynn2019** [comment]
Here you go...
[index_sample.txt](https://github.com/asciidoctor/asciidoctor-vscode/files/4162282/index_sample.txt)

**Comment by danyill** [comment]
Thanks @KLynn2019, seems to be related to the id. If I remove `[[Overview]]` it renders correctly.

I think but am not entirely sure the following is related.
There is a pile of errors occurring in the renderer log:

```
[2020-02-06 11:16:27.422] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError): [object Object]): Error: Unable to read file (EntryNotFound (FileSystemError): [object Object])
    at _.doReadAsFileStream (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-02-06 11:16:28.838] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError): [object Object]): Error: Unable to read file (EntryNotFound (FileSystemError): [object Object])
    at _.doReadAsFileStream (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-02-06 11:16:30.807] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError): [object Object]): Error: Unable to read file (EntryNotFound (FileSystemError): [object Object])
    at _.doReadAsFileStream (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-02-06 11:16:35.877] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError): [object Object]): Error: Unable to read file (EntryNotFound (FileSystemError): [object Object])
    at _.doReadAsFileStream (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-02-06 11:16:38.053] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError): [object Object]): Error: Unable to read file (EntryNotFound (FileSystemError): [object Object])
    at _.doReadAsFileStream (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-02-06 11:16:39.618] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError): [object Object]): Error: Unable to read file (EntryNotFound (FileSystemError): [object Object])
    at _.doReadAsFileStream (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-02-06 11:16:40.777] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError): [object Object]): Error: Unable to read file (EntryNotFound (FileSystemError): [object Object])
    at _.doReadAsFileStream (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

And also in the extension log:

```
[2020-02-06 11:16:28.474] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:28.639] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:30.482] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:30.566] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:30.604] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:30.628] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:30.950] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:31.123] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:35.671] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:37.404] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:37.579] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:37.658] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:37.684] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:37.722] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:37.872] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:39.414] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:40.571] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
[2020-02-06 11:16:41.975] [exthost] [warning] DiagnosticCollection with name 'languageErrors' does already exist.
```

Not sure what this means yet. I'll have a look...

**Comment by danyill** [comment]
OK, we have a well defined error when debugging:

```
rejected promise not handled within 1 second: TypeError: Cannot read property '1' of null
extensionHostProcess.js:820
stack trace: TypeError: Cannot read property '1' of null
	at AsciidocContentProvider.<anonymous> (/home/mulhollandd/Documents/asciidoctor-vscode/out/src/features/previewContentProvider.js:70:30)
	at Generator.next (<anonymous>)
	at fulfilled (/home/mulhollandd/Documents/asciidoctor-vscode/out/src/features/previewContentProvider.js:7:58)
```

The cause is a change I made to handle the toc left/right issue. I can do a PR for this @joaompinto
