### ISSUE TITLE
Command 'Asciido: Export document as PDF' Resulted in an error

### ISSUE THREAD

**Issue by Johan1974** [asciidoctor/asciidoctor-vscode#521]
Hello,

When i try to create a PDF i get the following error:

Command 'Asciido: Export document as PDF' Resulted in an error (Cannot red property 'startsWith' of underfined)

It used to work fine so not sure what to do with this one. 

Greetings,

Johan
Windows 10 Pro
VSCode 1.64.2
AsciiDoc v2.9.4

**Comment by Johan1974** [comment]
I see the folowing lines in the error log

> [2022-02-17 12:44:10.832] [exthost] [error] TypeError: Cannot read property 'startsWith' of undefined
	at ExportAsPDF.<anonymous> (c:\Users\Johan\.vscode\extensions\asciidoctor.asciidoctor-vscode-2.9.4\dist\src\commands\exportAsPDF.js:93:56)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\Johan\.vscode\extensions\asciidoctor.asciidoctor-vscode-2.9.4\dist\src\commands\exportAsPDF.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) asciidoc.exportAsPDF {"value":"asciidoctor.asciidoctor-vscode","_lower":"asciidoctor.asciidoctor-vscode"}

**Comment by Mogztter** [comment]
Duplicate https://github.com/asciidoctor/asciidoctor-vscode/issues/509
