### ISSUE TITLE
Preview crashes: Cannot read properties of undefined (reading 'resource')

### ISSUE THREAD

**Issue by jmvermeulen** [asciidoctor/asciidoctor-vscode#622]
On VS Code 1.70.1 using the AsciiDoc extention the preview windows crashes.
It stays empty and after +-15 sec VS Codes seems to crash. The file to preview is not relevant, its more or less empty.

Running on Kubuntu 22.04

Version: 1.70.1
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:09:15.055Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-43-generic

The error in the log:

```
[2022-08-15 09:28:38.851] [renderer1] [error] Cannot read properties of undefined (reading 'resource'): TypeError: Cannot read properties of undefined (reading 'resource')
	at Function.<anonymous> (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.9.8/dist/src/features/preview.js:123:53)
	at Generator.next (<anonymous>)
	at /home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.9.8/dist/src/features/preview.js:30:71
	at new Promise (<anonymous>)
	at __awaiter (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.9.8/dist/src/features/preview.js:26:12)
	at Function.revive (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.9.8/dist/src/features/preview.js:122:16)
	at AsciidocPreviewManager.<anonymous> (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.9.8/dist/src/features/previewManager.js:93:61)
	at Generator.next (<anonymous>)
	at /home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.9.8/dist/src/features/previewManager.js:30:71
	at new Promise (<anonymous>)
	at __awaiter (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.9.8/dist/src/features/previewManager.js:26:12)
	at AsciidocPreviewManager.deserializeWebviewPanel (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.9.8/dist/src/features/previewManager.js:92:16)
	at i.$deserializeWebviewPanel (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:199532)
	at o._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13691)
	at o._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13373)
	at o._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:12143)
	at o._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:10845)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:8952
	at w.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at b.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:17079
	at w.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at b.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19006)
	at i._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:23593)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:21127
	at w.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at b.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15837)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:14967
	at Socket.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:26303)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
```

**Comment by jmvermeulen** [comment]
I've opened and closed VS Code multiple times. All documents are closed.

**Comment by Mogztter** [comment]
I cannot reproduce this issue:

![image](https://user-images.githubusercontent.com/333276/184813773-d290020f-ff69-4f82-ac5f-b6e0bf488c85.png)

**Comment by jmvermeulen** [comment]
Tried to uninstall VS Code, clear the /.config/code directory. Is there any cache or other folder I could remove for a "fresh" start?

**Comment by Mogztter** [comment]
Not sure... maybe try the latest (beta) version 3.x?

**Comment by ggrossetie** [comment]
Since I cannot reproduce this issue, I'm closing. Feel free to reopen with additional information/context if you can still reproduce this issue using the latest version.
