### ISSUE TITLE
Error: Illegal argument: line must be non-negative from tableOfContentsprovider

### ISSUE THREAD

**Issue by apupier** [asciidoctor/asciidoctor-vscode#736]
Noticed this stacktrace in console:

```
[Extension Host] Unable to build the Table Of Content for: /home/apupier/ws/asciidoc/my.adoc Error: Illegal argument: line must be non-negative
	at m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1267)
	at new s (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13490)
	at /home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/tableOfContentsProvider.js:60:61
	at Array.map (<anonymous>)
	at TableOfContentsProvider.buildToc (/home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/tableOfContentsProvider.js:55:14)
	at TableOfContentsProvider.getToc (/home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/tableOfContentsProvider.js:37:33)
	at AsciidocFoldingRangeProvider.getHeaderFoldingRanges (/home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/features/foldingProvider.js:149:57)
	at AsciidocFoldingRangeProvider.provideFoldingRanges (/home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/features/foldingProvider.js:34:36)
	at we.provideFoldingRanges (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:59868)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:75474
	at oe.s (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:63904)
	at oe.$provideFoldingRanges (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:75460)
	at s.N (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11717)
	at s.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11435)
	at s.H (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10477)
	at s.G (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9494)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:8282
	at b.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at d.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:32461
	at b.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at d.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30587)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
	at Object.callbackTrampoline (node:internal/async_hooks:130:17) (at console.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:161026))
```

The mentioned file content is:
```
= test
include::attrs.adoc[]


content

```

and the content of attrs.adoc is:
```:a-attr3: value3```

**Comment by ggrossetie** [comment]
I guess the error is thrown here: https://github.com/asciidoctor/asciidoctor-vscode/blob/45302b52a57c8e3ffdd37cdca3a4f7145df7be23/src/tableOfContentsProvider.ts#L54C16-L54C16

```ts
new vscode.Position(section.getLineNumber() - 1, 1))
```

`section.getLineNumber()` must return 0.

**Comment by ggrossetie** [comment]
Good news is we have a test class: https://github.com/asciidoctor/asciidoctor-vscode/blob/master/src/test/tableOfContentsProvider.test.ts 😉

**Comment by apupier** [comment]
to reproduce the issue, a valid include statement must be placed just below the section title
