### ISSUE TITLE
CTRL-Click to open file stopped working in 3.1.0

### ISSUE THREAD

**Issue by glynb** [asciidoctor/asciidoctor-vscode#748]
```
= Parent Doc

include::child.adoc[]
```

in version 2.9.8 CTRL-click of filename "child.adoc" would open child.adoc in the editor. This no longer works in 3.1.0

reinstalling 2.9.8 brings the capability back

**Comment by ggrossetie** [comment]
Thanks for your report! I will add a test case to reproduce and fix this issue.

**Comment by ggrossetie** [comment]
I cannot reproduce it (and we already have test cases):

![ok](https://github.com/asciidoctor/asciidoctor-vscode/assets/333276/300d1eb4-bd5c-4fa6-8397-0aa5f7c529fc)


Could you please provide your settings and a screencast?

**Comment by ggrossetie** [comment]
Make sure that  `"editor.links": false` is not defined in your settings.

**Comment by glynb** [comment]
Hi, thanks for looking at this so quickly....here is screen recording of everything working in 2.9.8

https://github.com/asciidoctor/asciidoctor-vscode/assets/31587300/d6bb7631-6ab9-409c-8f62-eca5ed3a210c

**Comment by glynb** [comment]
Here is screen cast of update to 3.1.0 on the same workspace....

https://github.com/asciidoctor/asciidoctor-vscode/assets/31587300/c68b472f-f3e1-4a2c-971c-93598726a0c3

**Comment by glynb** [comment]
System: Windows 10 Enterprise
Version: 20H2
VSCode : 1.80.1

And here are the settings...

{
    "files.autoSave": "afterDelay",
    "cSpell.language": "en-gb",
    "cSpell.customUserDictionaries": [
    
    ],
    "pandoc.htmlOptString": "-N",
    "cSpell.userWords": [
        "ICCS"
    ],
    "insertDateString.format": "DD-MMM-YYYY",
    "explorer.confirmDragAndDrop": false,
    "security.workspace.trust.untrustedFiles": "open",
    "[python]": {
        "editor.formatOnType": true
    },
    "cSpell.diagnosticLevel": "Hint",
    "redhat.telemetry.enabled": true,
    "xml.symbols.maxItemsComputed": 500000,
    "[xml]": {
        "editor.defaultFormatter": "redhat.vscode-xml"
    },
    "editor.largeFileOptimizations": false,
    "asciidoc.preview.useEditorStyle": false,
    "asciidoc.extensions.registerWorkspaceExtensions": true,
    "asciidoc.useWorkspaceRootAsBaseDirectory": true,
    "asciidoc.debug.enableErrorDiagnostics": false
}

**Comment by glynb** [comment]
And,  "editor.links": false is not defined in my settings. Thanks

**Comment by ggrossetie** [comment]
Could you please install the latest version, restart VS code then click on "Help" > "Toggle Developer Tools". Click on the "Console" tab of the DevTools. Any errors, messages?


Apart from that, the activation time is very slow. On my machine it takes 120ms. As you can see on your video, the extension is only fully loaded at the very end (when "12232ms" becomes visible).

**Comment by ggrossetie** [comment]
I found a bug related to Windows. I will release a new version tomorrow, hopefully it will fix this issue.

**Comment by glynb** [comment]
Hi, error in log below. The adoc files used are as per the video clip and are below the log, neither have a :toc: ....

log.ts:421  INFO [perf] Render performance baseline is 64ms
console.ts:137 [Extension Host] Unable to build the Table Of Content for: c:\adoctest\parent.adoc Error: Illegal value for `line`
	at v.t (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:961)
	at Object.lineAt (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:90)
	at c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\tableOfContentsProvider.js:78:197
	at Array.map (<anonymous>)
	at TableOfContentsProvider.buildToc (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\tableOfContentsProvider.js:69:20)
	at TableOfContentsProvider.getToc (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\tableOfContentsProvider.js:37:33)
	at AdocDocumentSymbolProvider.<anonymous> (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\features\documentSymbolProvider.js:58:99)
	at Generator.next (<anonymous>)
	at c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\features\documentSymbolProvider.js:30:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\features\documentSymbolProvider.js:26:12)
	at AdocDocumentSymbolProvider.provideDocumentSymbols (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\features\documentSymbolProvider.js:54:16)
	at o.provideDocumentSymbols (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:37276)
	at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:63553
	at se.s (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:62833)
	at se.$provideDocumentSymbols (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:63542)
	at t.N (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11199)
	at t.M (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10965)
	at t.H (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10007)
	at t.G (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9122)
	at i.value (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:7952)
	at p.w (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at i.value (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30341)
	at p.w (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
log.ts:441   ERR Cannot read properties of undefined (reading 'forEach'): TypeError: Cannot read properties of undefined (reading 'forEach')
	at findNearest (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\similarArrayMatch.js:59:18)
	at c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\similarArrayMatch.js:107:37
	at Array.forEach (<anonymous>)
	at similarArrayMatch (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\similarArrayMatch.js:104:17)
	at LinkProvider.provideDocumentLinks (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\features\documentLinkProvider.js:142:81)
	at Q.provideLinks (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:57517)
	at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:73122
	at se.s (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:62833)
	at se.$provideDocumentLinks (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:73111)
	at t.N (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11199)
	at t.M (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10965)
	at t.H (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10007)
	at t.G (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9122)
	at i.value (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:7952)
	at p.w (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at i.value (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30341)
	at p.w (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
console.ts:137 [Extension Host] Unable to build the Table Of Content for: c:\adoctest\parent.adoc Error: Illegal value for `line`
	at v.t (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:961)
	at Object.lineAt (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:90)
	at c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\tableOfContentsProvider.js:78:197
	at Array.map (<anonymous>)
	at TableOfContentsProvider.buildToc (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\tableOfContentsProvider.js:69:20)
	at TableOfContentsProvider.getToc (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\tableOfContentsProvider.js:37:33)
	at AsciidocFoldingRangeProvider.getHeaderFoldingRanges (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\features\foldingProvider.js:149:57)
	at AsciidocFoldingRangeProvider.provideFoldingRanges (c:\Users\xxx\.vscode\extensions\asciidoctor.asciidoctor-vscode-3.1.0\dist\src\features\foldingProvider.js:34:36)
	at De.provideFoldingRanges (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:58873)
	at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:74116
	at se.s (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:62833)
	at se.$provideFoldingRanges (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:74102)
	at t.N (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11199)
	at t.M (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10965)
	at t.H (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:10007)
	at t.G (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9122)
	at i.value (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:7952)
	at p.w (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at i.value (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30341)
	at p.w (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:1902)
	at p.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:60:2119)
	at f.fire (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)

------------------------------------
= Parent

include::child.adoc[]

// filename is not underlined and can be cant ctrl-clicked

--------------------------------------

= Child

I'm the child doc

**Comment by glynb** [comment]
Updated from 3.1.0 to the new  3.1.2 and ctrl-click to open included files is working

*Many thanks*
