### ISSUE TITLE
preview stopped working on vscode.dev

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/asciidoctor-vscode#770]
i've been using asciidoctor split preview on vscode.dev just fine until recently when I got tired of vscode.dev saying I needed to update the extension. When I reloaded vscode.dev I can no longer preview  - it says: `command 'asciidoc.showLockedPreviewToSide' not found`

I tried restarting but no luck.

unfortunately I did not take notice what old version I was running - I'm now running v3.1.3

**Comment by ggrossetie** [comment]
You were probably running 3.0.x or 2.9.8.

The error indicates that the extension does not properly load. I will try to troubleshoot this issue next week.

Any error/stacktraces in the developer console? Do you see anything particular when you have install/uninstall the extension?

**Comment by ggrossetie** [comment]
```
Activating extension 'asciidoctor.asciidoctor-vscode' failed: process is not defined.
overrideMethod @ console.js:213
$onExtensionActivationError @ mainThreadExtensionService.ts:113
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
w @ event.ts:1089
fire @ event.ts:1120
N.onmessage @ webWorkerExtensionHost.ts:215
Show 1 more frame
Show less
```

**Comment by ggrossetie** [comment]
```
ReferenceError: process is not defined
	at module.exports (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:64476:18)
	at __webpack_require__ (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:135502:42)
	at Object.eval (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:62282:20)
	at __webpack_require__ (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:135502:42)
	at Object.eval (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:62122:20)
	at __webpack_require__ (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:135502:42)
	at Object.eval (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:59441:17)
	at __webpack_require__ (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:135502:42)
	at Object.eval (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:55051:33)
	at __webpack_require__ (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:135502:42)
	at Object.eval (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:60:25)
	at __webpack_require__ (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:135502:42)
	at eval (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:135560:37)
	at eval (https://asciidoctor.vscode-unpkg.net/asciidoctor/asciidoctor-vscode/3.1.3/extension/dist/browser/extension.js#vscode-extension:135565:12)
	at R.rb (../../../vs/workbench/api/worker/extensionHostWorker.js:91:627)
	at async Promise.all (index 0)
	at async o.n (../../../vs/workbench/api/worker/extensionHostWorker.js:80:6207)
	at async o.m (../../../vs/workbench/api/worker/extensionHostWorker.js:80:6170)
	at async o.l (../../../vs/workbench/api/worker/extensionHostWorker.js:80:5627)
```

**Comment by jonathan-s** [comment]
@ggrossetie 
<img width="354" alt="Screenshot 2023-08-22 at 12 53 30" src="https://github.com/asciidoctor/asciidoctor-vscode/assets/2124818/9488615d-2d5b-4dca-8d96-2b24feff1385">

I'm having this issue as well, and I'm running the latest version on my local machine. Not sure how I can resolve this.

**Comment by maxandersen** [comment]
I don't think the fix in #781 was part of a release yet ? 

At least I only see 3.1.3 available.

Any ETA on when the fix could be available to use?

**Comment by ggrossetie** [comment]
> I'm having this issue as well, and I'm running the latest version on my local machine. Not sure how I can resolve this.

I don't think this is related. This issue is specific to the Web environment (vscode.dev).
@jonathan-s You should enable the developer tools and look for an error in the console when you activate the extension.

> I don't think the fix in https://github.com/asciidoctor/asciidoctor-vscode/issues/781 was part of a release yet ?

No release yet 😉 

> Any ETA on when the fix could be available to use?

Probably next week.

**Comment by jonathan-s** [comment]
@ggrossetie Thanks! This was the error that I saw in the logs. Also when creating a bug issue. It might be helpful to include this line in the bug issue template so when new issues are created this would be included. (I found it in contribution.md)  

```
The extension logs — Go to the Command Palette and select the option 'Developer: Open Extension Logs Folder'.
```

error log
```
2023-08-22 17:20:25.434 [info] ExtensionService#_doActivateExtension asciidoctor.asciidoctor-vscode, startup: false, activationEvent: 'onLanguage:asciidoc'
2023-08-22 17:20:26.290 [error] Activating extension asciidoctor.asciidoctor-vscode failed due to an error:
2023-08-22 17:20:26.290 [error] __dir__: undefined method `__dir__' for Asciidoctor
    at Function.$$method_missing (/Users/jonathan/.vscode/extensions/bcherny.better-asciidoc-vscode-0.0.7/node_modules/opal-runtime/src/opal.js:3851:56)
    at Function.method_missing_stub (/Users/jonathan/.vscode/extensions/bcherny.better-asciidoc-vscode-0.0.7/node_modules/opal-runtime/src/opal.js:1287:35)
    at /Users/jonathan/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.1.3/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:21508:112
    at /Users/jonathan/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.1.3/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:21677:5
    at /Users/jonathan/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.1.3/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:21710:3
    at Object.<anonymous> (/Users/jonathan/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.1.3/src/asciidoctorWebViewConverter.ts:15:47)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/jonathan/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.1.3/src/asciidocEngine.ts:2:1)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.<anonymous> (/Users/jonathan/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.1.3/src/extension.ts:23:1)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:98)
    at i.rb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:26583)
    at async Promise.all (index 0)
```

**Comment by ggrossetie** [comment]
You should remove `bcherny.better-asciidoc-vscode-0.0.7`. Apparently it conflicts with `asciidoctor.asciidoctor-vscode-3.1.1`

**Comment by ggrossetie** [comment]
> This was the error that I saw in the logs. Also when creating a bug issue. It might be helpful to include this line in the bug issue template so when new issues are created this would be included. (I found it in contribution.md)

That's a good idea, you can submit a pull request to include it: https://github.com/asciidoctor/asciidoctor-vscode/blob/master/.github/ISSUE_TEMPLATE/report-a-problem.md

**Comment by jonathan-s** [comment]
Brilliant, thanks a lot. It's working now, and I've learnt something new that might come in handy for debugging other extensions.

**Comment by ggrossetie** [comment]
Awesome 😎
