### ISSUE TITLE
Test "Antora support with single documentation component" is flaky

### ISSUE THREAD

**Issue by ViToni** [asciidoctor/asciidoctor-vscode#856]
Hit the issue only once locally and once in a pipeline but still unexpected:

* What you're trying to do: Executing `npm run test` on `master`
* What happened: Test is flaky:
```
  1) Antora support with single documentation component
       Should build content catalog:
     TypeError: Cannot read properties of undefined (reading 'getImages')
  	at /Users/vtoni/git/asciidoctor-vscode/dist/src/test/antoraSupport.test.js:219:35
  	at Generator.next (<anonymous>)
  	at fulfilled (dist/src/test/antoraSupport.test.js:28:58)
```
Re-executing `npm run test` doesn't hit the failing test
* What you expected to happen: Test should be stable

I've seen the test also fail in a Windows pipeline (not `master`, feature branch with unrelated changes):
* https://github.com/asciidoctor/asciidoctor-vscode/actions/runs/8307511948/job/22736788637#step:8:237

System Info
Commit: acbb89000276bc1541b2c66385009f59645b3d60
Date: 2024-03-17T19:45+01:00
Node.js: 18.14.2
OS: MacOS Sonoma 14.4

**Comment by ggrossetie** [comment]
The following function returns `undefined`:
 https://github.com/asciidoctor/asciidoctor-vscode/blob/2235846a3708171e01a3076e354292c6a6d835e1/src/features/antora/antoraSupport.ts#L266

Since there's no error in the console, `antoraSupportManager.isEnabled()` might return false:

https://github.com/asciidoctor/asciidoctor-vscode/blob/2235846a3708171e01a3076e354292c6a6d835e1/src/features/antora/antoraSupport.ts#L268-L270

Or we cannot find an Antora context for the given file:
https://github.com/asciidoctor/asciidoctor-vscode/blob/2235846a3708171e01a3076e354292c6a6d835e1/src/features/antora/antoraSupport.ts#L313-L315

We should probably add a logger to help troubleshoot.

**Comment by ggrossetie** [comment]
The Antora support has undergone a big overhaul, and I'm no longer reproducing the flakiness of the test.
